add_newline = true
continuation_prompt = "     "

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
truncate_to_repo = false

[git_branch]
symbol = "î‚  "
always_show_remote = true

[git_commit]
tag_symbol = " ğŸ”– "
tag_disabled = false

[git_status]
format = '($all_status$ahead_behind($style) )'
#format = '(\[$all_status$ahead_behind\]($style) )'
conflicted	= "âŒ"
ahead	= "ğŸ”¼"
behind	= "ğŸ”½"
diverged	= "ğŸ”€"
up_to_date	= ""
untracked	= "âœ¨"
stashed	= "ğŸ§ª"
modified	= "ğŸ“"
staged	= "ğŸš"
renamed	= "ğŸ¦‹"
deleted	= "ğŸ”¥"

[aws]
symbol = "â›… "

[character]
success_symbol = "ğŸ§"
error_symbol = "ğŸ‘€"

[cmd_duration]
min_time = "5_000"
#show_notifications = true
#min_time_to_notify = "45_000"

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[hostname]
ssh_only = true

[kubernetes]
symbol = "ğŸ”±"
disabled = false

[python]
symbol = "ğŸª±"
python_binary = "python3"

[sudo]
disabled = false
symbol = "ğŸ§™â€â™€ï¸"

[terraform]
disabled = false
symbol = "ğŸ’ "


############
# disabled #
############

#[jobs]
#symbol = "ğŸ‘·"


#####################
# not supported yet #
#####################

#[localip]
#disabled = false
#ssh_only = true

#[container]
#symbol = "ğŸ“¦"


